### ISSUE TITLE
[HTTPS] GET... failed, error: connection refused

### ISSUE THREAD

**Issue by zunedaalim** [techiesms/ESP32-ChatGPT#10]
In the file CloudSpeechClient.cpp, I am getting this error and can't seem to resolve it , please help
serial monitor output:
04:48:40.249 -> Record start!
04:48:40.249 -> 
04:48:43.037 -> Recoding Complited Processing
04:48:50.588 -> Json daata--please racket-
04:48:50.627 -> Asking Chat GPT
04:48:50.627 -> [HTTPS] begin...
04:48:50.627 -> [HTTPS] GET...
04:48:50.862 -> [HTTPS] GET... failed, error: connection refused
04:48:50.862 -> To ask againPress button

**Comment by Omkarxzy** [comment]
hey i am also getting an same error.
having you solved the issue?

**Comment by zunedaalim** [comment]
Yeah, I've solved it, the issue seems to be the SSL certificate.
[Here is the working code](https://github.com/zunedaalim/ChatGPT-AI-Assistant)

**Comment by Omkarxzy** [comment]
thanks.
I found that the json format techiesms is using is the old format.
and with some help from the claude AI i solved it by using the latest format

**Comment by Omkarxzy** [comment]
> Yeah i've solved it, the issue seems to be the ssl certificate, i'll share the code soon

did you make the "ESP32 Voice Assistant with ChatGPT" with two esp32 ?
or just one?

**Comment by zunedaalim** [comment]
> > Yeah i've solved it, the issue seems to be the ssl certificate, i'll share the code soon
> 
> did you make the "ESP32 Voice Assistant with ChatGPT" with two esp32 ?
> or just one?

I used two esp32 , but there is still a delay of atleast 5sec to get the output

**Comment by Omkarxzy** [comment]
5 sec sounds alot.
i am trying to use only one esp32 if possible.
I am modifying the  [https://github.com/techiesms/ESP32-ChatGPT/tree/main/Speech_To_Text_ESP32](speech_to_text_esp32 code) he has provided.
I am basically thinking of naming this audio.h library as speech.h by modifying it.
do you think it will work?

**Comment by zunedaalim** [comment]
> 5 sec sounds alot. i am trying to use only one esp32 if possible. I am modifying the [https://github.com/techiesms/ESP32-ChatGPT/tree/main/Speech_To_Text_ESP32](speech_to_text_esp32 code) he has provided. I am basically thinking of naming this audio.h library as speech.h by modifying it. do you think it will work?

Well, I couldn't comment without looking at your code, but based on the video, the two audio libraries will cause issues if used in the same .ino code. I didn't try it, but it's worth a shot. Good luck :)

**Comment by Omkarxzy** [comment]
we also settled on using two esp boards in the end.
as our project evaluation is tomorrow, just don't have time to tinker around
