### ISSUE TITLE
i2s_read_bytes' was not declared in this scope 

### ISSUE THREAD

**Issue by LabibProjects** [techiesms/ESP32-ChatGPT#7]
Hello sir,
I was working on a project using chatgpt server to make a chatbot. /tmp/174451025/esp32_CloudSpeech/I2S.cpp:57:10: error: 'i2s_read_bytes' was not declared in this scope. But I am having this issue please help me out. I have tried different times to solve it but having same issue all time. 
![Screenshot 2023-12-23 211158](https://github.com/techiesms/ESP32-ChatGPT/assets/133244520/22cfe6b0-a940-4f21-8b95-10355b1d8247)

**Comment by jclaudiomelo** [comment]
int I2S::Read(char* data, int numData) {
  size_t bytesRead = 0;
  i2s_read(I2S_NUM_0, data, numData, &bytesRead, portMAX_DELAY);
  return bytesRead;
}

try replace

**Comment by techiesms** [comment]
For this code particularly, try to reduce the ESP32 Boards Package version to 1.0.6 and then it will compile successfully

**Comment by muhammadmemon749** [comment]
I had the same issue and after version 1.0.6, it gave me this error: 
exec: "python": executable file not found in $PATH

Compilation error: exec: "python": executable file not found in $PATH
